export const TableData = [
    {
        id: "LegalEntityTypeMst",
        name: "Legal Entity Type",
        postEndpoint: "/api/v1/LegalEntityType",
        deleteEndpoint: "",
    },
    {
        id: "LegalEntityTypeDetailM",
        name: "Legal Entity Type Detail",
        postEndpoint: "/api/v1/LegalEntityTypeDetail",
        deleteEndpoint: "",
    },
    {
        id: "RoleMst",
        name: "Role",
        postEndpoint: "/api/v1/Role",
        deleteEndpoint: "",
    },
    {
        id: "FeatureMst",
        name: "Feature",
        postEndpoint: "/api/v1/Feature",
        deleteEndpoint: "",
    },
    {
        id: "SubscriptionMst",
        name: "Subscription",
        postEndpoint: "/api/v1/Subscription",
        deleteEndpoint: "",
    },
    {
        id: "SubscriptionConfigurat",
        name: "Subscription Configuration",
        postEndpoint: "/api/v1/SubscriptionConfiguration",
        deleteEndpoint: "",
    },
    {
        id: "FeatureRolePermissionM",
        name: "Feature Role Permission",
        postEndpoint: "/api/v2/FeatureRolePermission",
        deleteEndpoint: "",
    },
    {
        id: "DepartmentMst",
        name: "Department",
        postEndpoint: "/api/v1/Department",
        deleteEndpoint: "",
    },
    {
        id: "LegalEntity",
        name: "Legal Entity",
        postEndpoint: "/api/v1/LegalEntity",
        deleteEndpoint: "",
    },
    {
        id: "LegalEntityAddressMapping",
        name: "Legal Entity Address Mapping",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Users",
        name: "User",
        postEndpoint: "/api/v1/User",
        deleteEndpoint: "",
    },
    {
        id: "BankMst",
        name: "Banks",
        postEndpoint: "/api/v1/Banks",
        deleteEndpoint: "",
    },
    {
        id: "FiscalCalender",
        name: "Fiscal Calender",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "FiscalYear",
        name: "Fiscal Year",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Currency",
        name: "Currency",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "GLCodeFlagConfiguration",
        name: "GL Code Flag Configuration",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "ManageBank",
        name: "Manage Bank",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Customer",
        name: "Customer",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Vendor",
        name: "Vendor",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Payment",
        name: "Payment",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "GeneralLedger",
        name: "General Ledger",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "IncomeStatement",
        name: "Income Statement",
        postEndpoint: "",
        deleteEndpoint: "",
    },
]
