export const data = [
    {
        id: "LegalEntityType",
        name: "Legal Entity Type",
        postEndpoint: "/api/v{version}/LegalEntityType",
        deleteEndpoint: "",
    },
    {
        id: "LegalEntityTypeDetail",
        name: "Legal Entity Type Detail",
        postEndpoint: "/api/v{version}/LegalEntityTypeDetail",
        deleteEndpoint: "",
    },
    {
        id: "Role",
        name: "Role",
        postEndpoint: "/api/v1/Role",
        deleteEndpoint: "",
    },
    {
        id: "Feature",
        name: "Feature",
        postEndpoint: "/api/v1/Feature",
        deleteEndpoint: "",
    },
    {
        id: "Subscription",
        name: "Subscription",
        postEndpoint: "/api/v{version}/Subscription",
        deleteEndpoint: "",
    },
    {
        id: "SubscriptionConfiguration",
        name: "Subscription Configuration",
        postEndpoint: "/api/v{version}/SubscriptionConfiguration",
        deleteEndpoint: "",
    },
    {
        id: "FeatureRolePermission",
        name: "Feature Role Permission",
        postEndpoint: "/api/v2/FeatureRolePermission",
        deleteEndpoint: "",
    },
    {
        id: "Department",
        name: "Department",
        postEndpoint: "/api/v{version}/Department",
        deleteEndpoint: "",
    },
    {
        id: "LegalEntity",
        name: "Legal Entity",
        postEndpoint: "/api/v{version}/LegalEntity",
        deleteEndpoint: "",
    },
    {
        id: "LegalEntityAddressMapping",
        name: "Legal Entity Address Mapping",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "User",
        name: "User",
        postEndpoint: "/api/v{version}/User",
        deleteEndpoint: "",
    },
    {
        id: "FiscalCalender",
        name: "Fiscal Calender",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "FiscalYear",
        name: "Fiscal Year",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Currency",
        name: "Currency",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "GLCodeFlagConfiguration",
        name: "GL Code Flag Configuration",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "ManageBank",
        name: "Manage Bank",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Customer",
        name: "Customer",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Vendor",
        name: "Vendor",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "Payment",
        name: "Payment",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "GeneralLedger",
        name: "General Ledger",
        postEndpoint: "",
        deleteEndpoint: "",
    },
    {
        id: "IncomeStatement",
        name: "Income Statement",
        postEndpoint: "",
        deleteEndpoint: "",
    },
]
